import type { UMKMDashboardData } from '@/types/umkm';

export const UMKM_MOCK: UMKMDashboardData = {
  kpis: [
    { id: 'mentions', label: 'Total Mentions', value: '24.618', delta: '▲ 18% vs kemarin', deltaTone: 'up', bar: 74 },
    { id: 'reach', label: 'Potential Reach', value: '128,4 jt', delta: '▲ 31% vs kemarin', deltaTone: 'up', bar: 86 },
    { id: 'engagement', label: 'Engagement', value: '3,21 jt', delta: '▲ 24% vs kemarin', deltaTone: 'up', bar: 68 },
    { id: 'sentiment', label: 'Net Sentiment', value: '+11', delta: '▼ 6 poin · tekanan hoaks pajak', deltaTone: 'down', bar: 55, accent: 'var(--pos)' },
    { id: 'issues', label: 'Isu Aktif', value: '7 · 1 tinggi', delta: 'SLA respons rata-rata 38 mnt', deltaTone: 'flat', bar: 40, barTone: 'red' },
    { id: 'health', label: 'Skor Kesehatan Isu', value: '82/100', delta: 'Terkendali · 17 konten di-takedown', deltaTone: 'up', bar: 82, barTone: 'green' },
  ],
  crisisKpis: [
    { id: 'sev', label: 'Isu Aktif per Severity', value: '1 tinggi · 2 sedang · 4 rendah', delta: '2 isu baru terdeteksi hari ini', deltaTone: 'flat', bar: 55, barTone: 'red' },
    { id: 'sla', label: 'SLA Berisiko Terlewat', value: '1', delta: 'Hoaks pajak · sisa SLA L2', deltaTone: 'down', bar: 30, barTone: 'red', accent: 'var(--neg)' },
    { id: 'td', label: 'Takedown Menunggu', value: '24', delta: '9 diproses · 12 dilaporkan · 3 antre', deltaTone: 'flat', bar: 48, barTone: 'red' },
    { id: 'vel', label: 'Velocity Negatif', value: '−18%', delta: 'Melandai sejak klarifikasi 08.30 WIB', deltaTone: 'up', bar: 62, barTone: 'green' },
  ],
  eduKpis: [
    { id: 'optin', label: 'Kontak Opt-in WA', value: '642 rb', delta: '▲ 38 rb minggu ini', deltaTone: 'up', bar: 72, barTone: 'green' },
    { id: 'sesi', label: 'Sesi WA Hari Ini', value: '18.412', delta: '▲ 44% saat isu memuncak', deltaTone: 'up', bar: 64, barTone: 'green' },
    { id: 'delivery', label: 'Delivery Blast', value: '97,2%', delta: 'Read rate 89% · 24 jam', deltaTone: 'flat', bar: 97, barTone: 'green' },
    { id: 'ctr', label: 'CTR Konten Edukasi', value: '21,4%', delta: '▲ 3,1 poin vs rata-rata', deltaTone: 'up', bar: 54, barTone: 'green' },
    { id: 'bot', label: 'Bot Deflection', value: '86%', delta: 'Hanya 14% perlu agen manusia', deltaTone: 'up', bar: 86, barTone: 'green' },
    { id: 'csat', label: 'CSAT Kanal', value: '4,6/5', delta: 'Dari 2.816 survei pasca-sesi', deltaTone: 'up', bar: 92, barTone: 'green' },
  ],
  sentiment: {
    pos: 35, neu: 41, neg: 24, net: 11,
    posCount: '8.616', neuCount: '10.093', negCount: '5.909',
  },
  emotions: [
    { name: 'Antisipasi', value: '0,71', color: '#F58220' },
    { name: 'Takut ▲', value: '0,66', color: '#4E7A6A' },
    { name: 'Percaya', value: '0,62', color: '#7FA65A' },
    { name: 'Marah ▲', value: '0,52', color: '#C7402D' },
    { name: 'Senang', value: '0,48', color: '#F2B233' },
    { name: 'Terkejut', value: '0,45', color: '#6FA8C9' },
    { name: 'Sedih', value: '0,31', color: '#5B7BA6' },
    { name: 'Jijik', value: '0,28', color: '#8A6FA8' },
  ],
  channels: [
    { name: 'TikTok', pct: 38, value: '38%', tone: 'orange' },
    { name: 'X (Twitter)', pct: 22, value: '22%', tone: 'orange' },
    { name: 'Instagram', pct: 14, value: '14%', tone: 'orange' },
    { name: 'Facebook', pct: 9, value: '9%', tone: 'orange' },
    { name: 'Portal berita', pct: 11, value: '11%', tone: 'dark' },
    { name: 'TV / Radio', pct: 6, value: '6%', tone: 'dark' },
  ],
  mapBubbles: [
    { name: 'DKI Jakarta', x: 263, y: 593, volume: 4842, sentiment: 'neg', socialPct: 82, issue: 'Hoaks pajak · negatif 34%' },
    { name: 'Banten', x: 246, y: 589, volume: 1210, sentiment: 'neg', socialPct: 74, issue: 'Amplifikasi hoaks pajak' },
    { name: 'Jawa Barat', x: 281, y: 608, volume: 3510, sentiment: 'neg', socialPct: 76, issue: 'Petugas palsu minta OTP' },
    { name: 'Jawa Tengah', x: 343, y: 610, volume: 2186, sentiment: 'pos', socialPct: 58, issue: 'Edukasi Tiga TIR via radio' },
    { name: 'DI Yogyakarta', x: 341, y: 629, volume: 684, sentiment: 'neu', socialPct: 71, issue: 'Pertanyaan jadwal CAPI' },
    { name: 'Jawa Timur', x: 395, y: 616, volume: 2968, sentiment: 'neu', socialPct: 69, issue: 'Campuran edukasi vs keluhan' },
    { name: 'Sumatera Utara', x: 84, y: 378, volume: 1542, sentiment: 'neg', socialPct: 64, issue: 'Penolakan pendataan pasar' },
    { name: 'Riau', x: 143, y: 446, volume: 512, sentiment: 'neu', socialPct: 66, issue: 'Pertanyaan pelaku usaha besar' },
    { name: 'Sumatera Selatan', x: 217, y: 522, volume: 640, sentiment: 'neg', socialPct: 61, issue: 'Modus penipuan OTP' },
    { name: 'Lampung', x: 229, y: 574, volume: 398, sentiment: 'neu', socialPct: 63, issue: 'Sosialisasi kecamatan' },
    { name: 'Kalimantan Barat', x: 319, y: 457, volume: 596, sentiment: 'neu', socialPct: 57, issue: 'Kebingungan jadwal petugas' },
    { name: 'Kalimantan Selatan', x: 436, y: 527, volume: 1184, sentiment: 'pos', socialPct: 41, issue: 'Liputan positif pencanangan' },
    { name: 'Kalimantan Timur', x: 486, y: 482, volume: 524, sentiment: 'pos', socialPct: 52, issue: 'Narasi ekonomi digital IKN' },
    { name: 'Sulawesi Selatan', x: 543, y: 569, volume: 802, sentiment: 'pos', socialPct: 55, issue: 'Dukungan asosiasi UMKM' },
    { name: 'Sulawesi Utara', x: 664, y: 424, volume: 385, sentiment: 'neu', socialPct: 60, issue: 'Sosialisasi sektor pariwisata' },
    { name: 'Bali', x: 452, y: 645, volume: 470, sentiment: 'pos', socialPct: 68, issue: 'Testimoni pelaku usaha' },
    { name: 'NTT', x: 636, y: 678, volume: 246, sentiment: 'neu', socialPct: 44, issue: 'Jangkauan wilayah terpencil' },
    { name: 'Maluku', x: 738, y: 538, volume: 212, sentiment: 'neu', socialPct: 49, issue: 'Logistik pendataan pulau' },
    { name: 'Papua', x: 1002, y: 512, volume: 210, sentiment: 'neu', socialPct: 38, issue: 'Koordinasi mitra lokal' },
  ],
  mapTop: [],
  escalation: {
    id: 'ISU-0041',
    title: 'Hoaks: “Data UMKM dipakai untuk menarik pajak & audit usaha”',
    description: '4.216 mentions · reach 38,2 jt · emosi dominan takut & marah pada segmen UMKM.',
    slaSeconds: 48 * 60 + 10,
    severity: 'high',
    levels: [
      {
        id: 'l1',
        label: 'L1',
        name: 'Analis Engagement Center',
        desc: 'Verifikasi, klasifikasi hoaks, kompilasi bukti',
        status: 'Selesai 11.05',
        state: 'done',
        assignee: 'EC Desk A',
        evidence: [
          'Screenshot viral TikTok @dagangnusantara (2,1 jt views)',
          'Thread X #DataUntukPajak · 840 RT',
          'Klasifikasi: HOAKS · severity HIGH',
        ],
      },
      {
        id: 'l2',
        label: 'L2',
        name: 'Tim Humas BPS & Mitra',
        desc: 'Klarifikasi resmi, media briefing, kontra-narasi',
        status: 'Berjalan',
        state: 'active',
        assignee: 'Humas Pusat',
        evidence: [
          'Draft press note v2 siap review',
          'WA blast segmen UMKM: queued 12k',
          'Briefing mitra media: 14.30 WIB',
        ],
      },
      {
        id: 'l3',
        label: 'L3',
        name: 'Pimpinan · Komdigi · BSSN',
        desc: 'Takedown terkoordinasi & pernyataan pimpinan',
        status: 'Siaga',
        state: 'pending',
        assignee: 'War Room',
        evidence: [
          'Paket takedown siap kirim ke Komdigi',
          'Draft pernyataan pimpinan (placeholder)',
          'Trigger: SLA L2 habis / velocity ↑',
        ],
      },
    ],
  },
  digitalArmy: {
    active: 248,
    stats: [
      { value: '312', label: 'Konten hari ini' },
      { value: '21,6 jt', label: 'Reach kumulatif' },
      { value: '4,2×', label: 'Rasio balas negatif' },
    ],
    tasks: [
      {
        name: 'Kontra-narasi hoaks pajak',
        meta: '86 konten · 64 personel · TikTok, X',
        headline: '86',
        progress: 72,
        pill: 'high',
        pillLabel: 'PRIORITAS',
        sparkline: [42, 48, 55, 52, 61, 68, 72, 78, 74, 86],
        actions: ['Deploy batch', 'Buka brief'],
      },
      {
        name: 'Amplifikasi liputan pencanangan',
        meta: '102 konten · 86 personel · X, YT',
        headline: '102',
        progress: 84,
        pill: 'ok',
        pillLabel: 'On Track',
        sparkline: [60, 62, 70, 74, 78, 80, 82, 85, 88, 102],
        actions: ['Boost reach', 'Share pack'],
      },
      {
        name: 'Edukasi Tiga TIR + petugas resmi',
        meta: '124 konten · 98 personel · IG, WA',
        headline: '124',
        progress: 58,
        pill: 'warn',
        pillLabel: 'Berjalan',
        sparkline: [30, 35, 40, 48, 52, 55, 50, 58, 62, 66],
        actions: ['Kirim WA', 'Jadwal slot'],
      },
      {
        name: 'Reply & stitch cepat',
        meta: '41 balasan · rasio 4,2× · 2 jam',
        headline: '4,2×',
        progress: 64,
        pill: 'warn',
        pillLabel: 'Berjalan',
        sparkline: [2.1, 2.4, 2.8, 3.1, 3.4, 3.6, 3.9, 4.0, 4.1, 4.2],
        actions: ['Assign reply', 'Seed stitch'],
      },
      {
        name: 'Reach kumulatif army',
        meta: '21,6 jt · 7 hari · multi-kanal',
        headline: '21,6 jt',
        progress: 76,
        pill: 'ok',
        pillLabel: 'On Track',
        sparkline: [8, 10, 12, 14, 15.5, 17, 18.2, 19.4, 20.5, 21.6],
        actions: ['Export reach', 'Bandingkan'],
      },
      {
        name: 'Konten produksi hari ini',
        meta: '312 asset · 248 personel aktif',
        headline: '312',
        progress: 69,
        pill: 'ok',
        pillLabel: 'On Track',
        sparkline: [180, 200, 220, 240, 255, 270, 280, 290, 300, 312],
        actions: ['Queue upload', 'Cek QC'],
      },
    ],
  },
  takedown: {
    chips: [
      { value: '41', label: 'Identified' },
      { value: '12', label: 'Reported' },
      { value: '9', label: 'In Process' },
      { value: '17', label: 'Takedown', highlight: true },
    ],
    items: [
      {
        title: 'Video “UMKM = sensor pajak UMKM”',
        meta: 'TikTok · reach 12,4 jt',
        status: 'proc',
        statusLabel: 'In Process',
        source: 'tiktok',
        reach: '12,4 jt',
        time: '2 jam lalu',
        channel: 'TikTok · @infoumkm.id',
        severity: 'high',
        preview: 'Klaim data sensus dipakai narik pajak — stitch viral.',
      },
      {
        title: 'Petugas palsu minta OTP & transfer',
        meta: 'Facebook · 3,1 jt · + laporan polisi',
        status: 'done',
        statusLabel: 'Takedown',
        source: 'facebook',
        reach: '3,1 jt',
        time: '5 jam lalu',
        channel: 'Facebook · grup UMKM',
        severity: 'high',
        preview: 'Akun meniru petugas BPS meminta OTP & transfer.',
      },
      {
        title: 'Portal “sensus-ekonomi-news.xyz”',
        meta: 'Situs abal meniru kanal BPS · 860 rb',
        status: 'rep',
        statusLabel: 'Reported',
        source: 'web',
        reach: '860 rb',
        time: 'Kemarin 18.40',
        channel: 'Web · domain abal',
        severity: 'medium',
        preview: 'Landing page palsu meniru identitas visual BPS.',
      },
      {
        title: 'Thread provokasi tolak petugas',
        meta: 'X · 2,2 jt · review platform',
        status: 'rev',
        statusLabel: 'Review',
        source: 'x',
        reach: '2,2 jt',
        time: '3 jam lalu',
        channel: 'X · thread',
        severity: 'low',
        preview: 'Ajakan menolak door-to-door; engagement sedang turun.',
      },
    ],
  },
  wa: {
    badge: '✓ Verified · Powered by BSP Partner',
    stats: [
      { value: '18.412', label: 'Sesi hari ini' },
      { value: '42 dtk', label: 'Median respons' },
      { value: '4,6/5', label: 'CSAT' },
      { value: '1.208', label: 'Cek fakta bot' },
      { value: '312', label: 'Pengaduan' },
      { value: '97,2%', label: 'Delivery blast' },
    ],
    intents: [
      { label: 'Verifikasi petugas resmi', pct: '34%' },
      { label: '“Apakah data untuk pajak?”', pct: '27%' },
      { label: 'Jadwal & cara pendataan', pct: '19%' },
    ],
  },
  keywords: [
    { text: '#UMKM', tone: 'pos' },
    { text: 'sensus ekonomi', tone: 'pos' },
    { text: 'pajak', tone: 'neg' },
    { text: 'petugas palsu', tone: 'neg' },
    { text: 'OTP penipuan', tone: 'neg' },
    { text: 'rahasia data' },
    { text: '#TigaTIR', tone: 'pos' },
    { text: 'UMKM' },
    { text: 'BPS' },
    { text: '#MencatatEkonomiIndonesia', tone: 'pos' },
    { text: 'tolak sensus', tone: 'neg' },
  ],
  posts: [
    {
      id: 'hp1',
      handle: '@infoumkm.id',
      platform: 'tiktok',
      excerpt:
        '“Hati-hati, katanya data sensus bakal dipakai buat narik pajak UMKM…” — video 58 dtk, dibantah stitch resmi.',
      likes: '84 rb',
      retweets: '12,4 rb',
      tone: 'rev',
      toneLabel: 'Negatif',
      influencer: true,
      sourceUrl: 'https://www.tiktok.com/',
      thumbTone: 'linear-gradient(145deg,#F97316,#FDBA74)',
    },
    {
      id: 'hp2',
      handle: '@BPS_Statistics',
      platform: 'x',
      excerpt:
        'Klarifikasi resmi: data UMKM dilindungi UU No. 16/1997 — hanya untuk statistik, bukan pajak.',
      likes: '31 rb',
      retweets: '2,8 jt',
      tone: 'done',
      toneLabel: 'Positif',
      verified: true,
      sourceUrl: 'https://x.com/',
      thumbTone: 'linear-gradient(145deg,#0F1419,#64748B)',
    },
    {
      id: 'hp3',
      handle: 'Media tier-1',
      platform: 'news',
      excerpt:
        '“Sensus Ekonomi 2026: general check-up ekonomi Indonesia” — liputan pencanangan & jaminan kerahasiaan data.',
      likes: '148',
      retweets: '26 jt',
      tone: 'done',
      toneLabel: 'Positif',
      verified: true,
      sourceUrl: 'https://www.bps.go.id/',
      thumbTone: 'linear-gradient(145deg,#1E8E5A,#86EFAC)',
    },
  ],
  crisisIssues: [
    {
      title: 'Hoaks “data untuk pajak & audit”',
      detail: 'Reach 38,2 jt · emosi takut+marah · ISU-0041',
      source: 'TikTok → X',
      mentions: '4.216 · ▲ cepat',
      sla: '0:48:00',
      pic: 'Koord. Krisis',
      status: 'L2 Berjalan',
      statusTone: 'proc',
      severity: 'high',
    },
    {
      title: 'Petugas palsu minta OTP / transfer',
      detail: 'Terlapor: Bekasi, Depok, Medan, Palembang',
      source: 'Facebook, WA',
      mentions: '1.318 · stabil',
      sla: '6:20:00',
      pic: 'Tim Verifikasi',
      status: 'Dilaporkan',
      statusTone: 'rep',
      severity: 'medium',
    },
    {
      title: 'Ajakan menolak pendataan door-to-door',
      detail: 'Komunitas pedagang pasar · 3 kota',
      source: 'X, komunitas FB',
      mentions: '842 · ▼ turun',
      sla: '11:05:00',
      pic: 'Humas Daerah',
      status: 'Mitigasi',
      statusTone: 'proc',
      severity: 'medium',
    },
    {
      title: 'Keluhan petugas belum berseragam lengkap',
      detail: 'Sporadis · 6 kab/kota',
      source: 'IG, portal lokal',
      mentions: '316 · stabil',
      sla: '22:00:00',
      pic: 'Koord. Lapangan',
      status: 'Monitor',
      statusTone: 'rev',
      severity: 'low',
    },
    {
      title: 'Situs abal meniru identitas BPS',
      detail: 'Domain sensus-ekonomi-news.xyz · phishing form',
      source: 'Web · laporan warga',
      mentions: '528 · ▲ lambat',
      sla: '18:40:00',
      pic: 'Tim Cyber',
      status: 'Dilaporkan',
      statusTone: 'rep',
      severity: 'low',
    },
    {
      title: 'Narasi “UMKM = sensor usaha kecil”',
      detail: 'Varian klaim di short-form · Jawa Barat & Sumut',
      source: 'TikTok, Reels',
      mentions: '704 · stabil',
      sla: '20:15:00',
      pic: 'Digital Army',
      status: 'Kontra-narasi',
      statusTone: 'proc',
      severity: 'low',
    },
    {
      title: 'FAQ “apakah data dibagikan ke DJP?”',
      detail: 'Lonjakan intent bot WA · bukan hoaks terstruktur',
      source: 'WA Official',
      mentions: '2.104 sesi · edukasi',
      sla: '23:50:00',
      pic: 'WA Desk',
      status: 'Edukasi',
      statusTone: 'done',
      severity: 'low',
    },
  ],
  crisisTimeline: [
    { time: '6 JUL · 19.02', text: 'Video hoaks tayang di TikTok @infoumkm.id — klaim data sensus untuk penarikan pajak UMKM.', tone: 'crit' },
    { time: '6 JUL · 21.40', text: 'Viral: 480 rb views, direpost 3 akun besar X. Velocity +212%.', tone: 'crit' },
    { time: '7 JUL · 08.30', text: 'Klarifikasi resmi BPS terbit (UU No. 16/1997) — dikutip 22 media.', tone: 'good' },
    { time: '7 JUL · 10.58', text: 'Varian baru terdeteksi di 3 akun TikTok → dieskalasi ke L2.', tone: 'neutral' },
    { time: '7 JUL · 13.05', text: 'Papan isu: 7 aktif · 1 tinggi · SLA L2 di bawah 1 jam.', tone: 'crit' },
  ],
  funnel: [
    { label: 'Terkirim', value: '84.216', pct: 100 },
    { label: 'Delivered', value: '82.358', pct: 97.8 },
    { label: 'Dibaca', value: '74.952', pct: 89 },
    { label: 'Klik CTA', value: '18.026', pct: 21.4 },
    { label: 'Aksi lanjut', value: '8.912', pct: 10.6 },
  ],
  botIntents: [
    { name: 'Verifikasi petugas', pct: 84, value: '34%', tone: 'green' },
    { name: 'Isu pajak', pct: 66, value: '27%', tone: 'green' },
    { name: 'Jadwal & cara', pct: 47, value: '19%', tone: 'green' },
    { name: 'Lapor hoaks', pct: 30, value: '12%', tone: 'green' },
    { name: 'Lainnya', pct: 20, value: '8%', tone: 'green' },
  ],
  calendar: [
    { schedule: '7 Jul · 14.00', theme: 'Klarifikasi: data bukan untuk pajak (UU 16/1997)', channel: 'WA blast, X, TikTok', format: 'Infografis + video 30 dtk', status: 'Menunggu rilis', statusTone: 'proc' },
    { schedule: '8 Jul · 09.00', theme: 'Cara verifikasi petugas resmi (cek ID via WA bot)', channel: 'WA, IG, radio lokal', format: 'Carousel + adlibs radio', status: 'Siap', statusTone: 'done' },
    { schedule: '8 Jul · 16.30', theme: 'FAQ “Apakah data dibagikan ke DJP?” — reply pack desk', channel: 'WA Official, X', format: 'FAQ bot + thread', status: 'Siap', statusTone: 'done' },
    { schedule: '9 Jul · 10.00', theme: 'Tiga TIR: Terima, Isi benar, Rahasia terjaga', channel: 'TikTok, FB, koran daerah', format: 'Video KOL + advertorial', status: 'Produksi', statusTone: 'proc' },
    { schedule: '10 Jul · 13.00', theme: 'UMKM mendata ekonomi digital & UMKM online', channel: 'X, YouTube, portal', format: 'Thread + explainer 90 dtk', status: 'Draft', statusTone: 'rep' },
    { schedule: '11 Jul · 09.30', theme: 'Testimoni pelaku usaha: data aman, manfaat statistik', channel: 'IG Reels, TikTok', format: 'UGC 45 dtk', status: 'Produksi', statusTone: 'proc' },
  ],
  eduChannels: [
    { name: 'WA Official', pct: 92, value: '21,4%', tone: 'green' },
    { name: 'TikTok', pct: 64, value: '9,8%', tone: 'orange' },
    { name: 'Instagram', pct: 48, value: '7,2%', tone: 'orange' },
    { name: 'X (Twitter)', pct: 33, value: '4,9%', tone: 'orange' },
    { name: 'Radio lokal', pct: 28, value: '4,1%', tone: 'dark' },
    { name: 'Facebook', pct: 24, value: '3,6%', tone: 'orange' },
  ],
  eduGrowth: [
    { week: 'W1', optin: 360, sessions: 9.2 },
    { week: 'W2', optin: 410, sessions: 11.4 },
    { week: 'W3', optin: 455, sessions: 13.1 },
    { week: 'W4', optin: 520, sessions: 14.8 },
    { week: 'W5', optin: 580, sessions: 16.5 },
    { week: 'W6', optin: 642, sessions: 18.4 },
  ],
  eduComplaints: [
    { label: 'Diselesaikan bot', value: '1.086', note: 'Hari ini' },
    { label: 'Eskalasi manusia', value: '122', note: '14% sesi' },
    { label: 'Tiket hoaks baru', value: '38', note: 'Dari WA' },
  ],
  eduBestContent: {
    title: 'Cek petugas resmi UMKM (30 dtk)',
    channel: 'TikTok',
    er: '9,4%',
    views: '2,1 jt',
  },
  ticker: [
    { tag: 'hoax', tagLabel: 'Hoaks', text: 'Varian baru video “sensus = pajak” terdeteksi di 3 akun TikTok — otomatis masuk antrean takedown' },
    { tag: 'edu', tagLabel: 'Edukasi', text: 'Blast WA “Kenali Petugas Resmi UMKM” gel. 2 terkirim ke 84.216 kontak · delivery 97,8%' },
    { tag: 'media', tagLabel: 'Media', text: 'TVRI & 4 TV nasional menayangkan liputan pendataan door-to-door dengan tone positif' },
    { tag: 'hoax', tagLabel: 'Penipuan', text: 'Laporan petugas palsu meminta OTP di Bekasi — tiket otomatis dibuat dari WA Official' },
    { tag: 'edu', tagLabel: 'Digital Army', text: 'Konten kontra-narasi ke-312 tayang · rasio balas komentar negatif 4,2×' },
    { tag: 'media', tagLabel: 'Cetak', text: '6 media cetak nasional memuat advertorial Tiga TIR edisi hari ini' },
  ],
  insight:
    'Lonjakan +212% percakapan negatif pada 6 Juli 19.00–23.00 WIB dipicu video TikTok hoaks “data UMKM dipakai untuk pajak”. Klarifikasi resmi menurunkan velocity −18%.',
};

UMKM_MOCK.mapTop = UMKM_MOCK.mapBubbles
  .slice()
  .sort((a, b) => b.volume - a.volume)
  .slice(0, 5);
