import type { UMKMDashboardData } from '@/types/umkm';

export const UMKM_MOCK: UMKMDashboardData = {
  kpis: [
    {
      id: 'sentiment',
      label: 'Sentimen Publik',
      value: '68% Positif',
      delta: '24% netral · 8% negatif',
      deltaTone: 'up',
      bar: 68,
      barTone: 'green',
      accent: 'var(--pos)',
    },
    {
      id: 'volume',
      label: 'Volume Pemberitaan (7 Hari)',
      value: '1.284',
      delta: '▲ 12% dibanding minggu lalu',
      deltaTone: 'up',
      bar: 72,
    },
    {
      id: 'sov',
      label: 'Share of Voice',
      value: '34%',
      delta: '▲ 5 poin (29% → 34%)',
      deltaTone: 'up',
      bar: 34,
    },
    {
      id: 'topissue',
      label: 'Isu Teratas',
      value: 'Konflik kepentingan mitra',
      delta: '410 rb reach · menunggu klarifikasi',
      deltaTone: 'flat',
      bar: 40,
      barTone: 'red',
    },
  ],
  programKpis: [
    {
      id: 'active',
      label: 'Program Aktif',
      value: '6',
      delta: 'Program prioritas tahun berjalan',
      deltaTone: 'flat',
      bar: 100,
      barTone: 'green',
    },
    {
      id: 'volume',
      label: 'Volume Pemberitaan Teratas',
      value: '356',
      delta: 'Program: Realisasi KUR · tertinggi 7 hari',
      deltaTone: 'up',
      bar: 70,
    },
    {
      id: 'sov',
      label: 'Share of Voice',
      value: '41%',
      delta: '▲ 6 poin (35% → 41%)',
      deltaTone: 'up',
      bar: 41,
    },
    {
      id: 'topissue',
      label: 'Isu Program Teratas',
      value: 'Keterlambatan pencairan KUR',
      delta: '268 rb reach · netral-negatif · dipantau',
      deltaTone: 'flat',
      bar: 45,
      barTone: 'red',
    },
  ],
  crisisKpis: [
    {
      id: 'sev',
      label: 'Isu Aktif per Severity',
      value: '1 tinggi · 2 sedang · 4 rendah',
      delta: '2 isu baru terdeteksi hari ini',
      deltaTone: 'flat',
      bar: 55,
      barTone: 'red',
    },
    {
      id: 'emotion',
      label: 'Emosi Dominan',
      value: 'Takut & Marah',
      delta: 'Didominasi isu Hoaks KUR & pinjaman online',
      deltaTone: 'down',
      bar: 66,
      barTone: 'red',
      accent: 'var(--neg)',
    },
    {
      id: 'mentions',
      label: 'Total Mentions Isu Aktif',
      value: '8.660',
      delta: 'Akumulasi 7 isu aktif · 7 hari terakhir',
      deltaTone: 'flat',
      bar: 70,
    },
    {
      id: 'vel',
      label: 'Velocity Negatif',
      value: '−18%',
      delta: 'Melandai sejak klarifikasi 08.30 WIB',
      deltaTone: 'up',
      bar: 62,
      barTone: 'green',
    },
  ],
  sentiment: {
    pos: 36,
    neu: 41,
    neg: 23,
    net: 13,
    posCount: '8.616',
    neuCount: '10.093',
    negCount: '5.909',
  },
  emotions: [
    { name: 'Antisipasi', value: '0,71', color: '#F58220' },
    { name: 'Percaya', value: '0,62', color: '#7FA65A' },
    { name: 'Senang', value: '0,48', color: '#F2B233' },
    { name: 'Sedih', value: '0,31', color: '#5B7BA6' },
    { name: 'Takut ▲', value: '0,66', color: '#4E7A6A' },
    { name: 'Marah ▲', value: '0,52', color: '#C7402D' },
    { name: 'Terkejut', value: '0,45', color: '#6FA8C9' },
    { name: 'Jijik', value: '0,28', color: '#8A6FA8' },
  ],
  channels: [
    { name: 'TikTok', pct: 38, value: '38%', tone: 'orange' },
    { name: 'X (Twitter)', pct: 22, value: '22%', tone: 'orange' },
    { name: 'Instagram', pct: 14, value: '14%', tone: 'orange' },
    { name: 'Facebook', pct: 9, value: '9%', tone: 'orange' },
    { name: 'YouTube', pct: 8, value: '8%', tone: 'dark' },
    { name: 'Online News', pct: 6, value: '6%', tone: 'dark' },
    { name: 'Threads', pct: 3, value: '3%', tone: 'dark' },
  ],
  mapBubbles: [
    // Centroid on indonesia-land.svg via path hit-test (viewBox 0 296 1024 430)
    { name: 'DKI Jakarta', x: 262, y: 605, volume: 412, sentiment: 'pos', socialPct: 74, issue: 'Percepatan realisasi KUR semester II · 74% positif' },
    { name: 'Jawa Barat', x: 298, y: 614, volume: 268, sentiment: 'pos', socialPct: 71, issue: 'Peresmian sentra UMKM digital · 71% positif' },
    { name: 'Jawa Tengah', x: 349, y: 622, volume: 240, sentiment: 'pos', socialPct: 79, issue: 'Kunjungan sentra sertifikasi halal' },
    { name: 'Jawa Timur', x: 396, y: 628, volume: 190, sentiment: 'pos', socialPct: 68, issue: 'Apresiasi kemudahan izin usaha UMKM · 68% positif' },
    { name: 'Sumatera Utara', x: 107, y: 418, volume: 96, sentiment: 'neu', socialPct: 46, issue: 'Opini soal target digitalisasi Sapa UMKM · 46% netral' },
    { name: 'Sulawesi Selatan', x: 550, y: 536, volume: 84, sentiment: 'pos', socialPct: 70, issue: 'Rencana kunjungan sentra sertifikasi halal' },
    { name: 'Kalimantan', x: 444, y: 462, volume: 45, sentiment: 'neu', socialPct: 52, issue: 'Sorotan realisasi KUR daerah · 52% netral' },
    { name: 'Bali', x: 450, y: 640, volume: 38, sentiment: 'pos', socialPct: 81, issue: 'Liputan program kewirausahaan muda · 81% positif' },
    { name: 'Papua', x: 930, y: 539, volume: 22, sentiment: 'neg', socialPct: 38, issue: 'Isu tudingan konflik kepentingan mitra program · 38% negatif' },
  ],
  mapTop: [],
  escalation: {
    id: 'ISU-0032',
    title: 'Hoaks: “Data KUR ditarik via tautan phishing / cicilan ganda”',
    description: '3.640 mentions · reach 12,8 jt · emosi dominan takut & marah pada segmen debitur KUR.',
    slaSeconds: 47 * 60 + 28,
    severity: 'high',
    levels: [
      {
        id: 'l1',
        label: 'L1',
        name: 'Analis Engagement Center',
        desc: 'Verifikasi, klasifikasi hoaks, kompilasi bukti',
        status: 'Selesai 21.45',
        state: 'done',
        assignee: 'EC Desk A',
        evidence: [
          'Video TikTok @infoumkm.id (10,2 jt reach)',
          'Repost X @beritaviral.id <2 jam',
          'Klasifikasi: HOAKS · severity HIGH',
        ],
      },
      {
        id: 'l2',
        label: 'L2',
        name: 'Koord. Krisis & Humas',
        desc: 'Klarifikasi resmi, media briefing, kontra-narasi',
        status: 'Berjalan',
        state: 'active',
        assignee: 'Koord. Krisis',
        evidence: [
          'Klarifikasi resmi dikutip 18 media',
          'Velocity negatif turun −18%',
          'Briefing mitra perbankan himbara',
        ],
      },
      {
        id: 'l3',
        label: 'L3',
        name: 'Pimpinan · Tim Cyber',
        desc: 'Takedown terkoordinasi & pernyataan pimpinan',
        status: 'Siaga',
        state: 'pending',
        assignee: 'War Room',
        evidence: [
          'Paket takedown siap untuk domain phishing KUR',
          'Draft pernyataan transparansi mitra program',
          'Trigger: SLA L2 habis / velocity ↑',
        ],
      },
    ],
  },
  keywords: [
    { text: 'umkm', tone: 'pos' },
    { text: 'usaha', tone: 'pos' },
    { text: 'ekonomi' },
    { text: 'program', tone: 'pos' },
    { text: 'pelaku' },
    { text: 'pembiayaan' },
    { text: 'masyarakat' },
    { text: 'pemerintah' },
    { text: 'indonesia' },
    { text: 'kredit' },
    { text: 'kur', tone: 'pos' },
    { text: 'sektor' },
    { text: 'daerah' },
    { text: 'bank' },
    { text: 'produk' },
    { text: 'bri' },
    { text: 'nasional' },
    { text: 'mikro' },
    { text: 'kegiatan' },
    { text: 'investasi' },
    { text: 'digital', tone: 'pos' },
    { text: 'kementerian', tone: 'pos' },
    { text: 'akses' },
    { text: 'kerja' },
    { text: 'sertifikasi halal', tone: 'pos' },
    { text: 'sapa umkm' },
    { text: 'cicilan ganda', tone: 'neg' },
    { text: 'phishing', tone: 'neg' },
    { text: 'penipuan', tone: 'neg' },
  ],
  posts: [
    {
      id: 'hp1',
      handle: '@ekonomi_rakyat',
      platform: 'x',
      excerpt:
        'Realisasi KUR semester ini lumayan cepat dibanding tahun lalu, semoga UMKM di daerah juga kebagian merata.',
      likes: '210',
      retweets: '42 rb',
      tone: 'done',
      toneLabel: 'Positif',
      score: 'C2 78/100',
      sourceUrl: 'https://x.com/',
      thumbTone: 'linear-gradient(145deg,#0F1419,#64748B)',
    },
    {
      id: 'hp2',
      handle: 'Forum UMKM Nusantara',
      platform: 'facebook',
      excerpt:
        'Ada yang udah coba daftar di Sapa UMKM? Aplikasinya lumayan membantu tapi proses verifikasinya agak lama...',
      likes: '165',
      retweets: '88,9 rb',
      tone: 'rev',
      toneLabel: 'Netral',
      score: 'C4 61/100',
      thumbTone: 'linear-gradient(145deg,#1877F2,#8AB4F8)',
    },
    {
      id: 'hp3',
      handle: '@ratnasari.umkm',
      platform: 'instagram',
      excerpt:
        'Alhamdulillah usaha keripik saya lolos sertifikasi halal',
      likes: '340',
      retweets: '15,2 rb',
      tone: 'done',
      toneLabel: 'Positif',
      score: 'C1 88/100',
      thumbTone: 'linear-gradient(145deg,#E1306C,#F77737)',
    },
    {
      id: 'hp4',
      handle: 'Kompas TV',
      platform: 'youtube',
      excerpt:
        'Liputan: Menteri UMKM tinjau langsung sentra sertifikasi halal',
      likes: '96',
      retweets: '20 jt',
      tone: 'rev',
      toneLabel: 'Netral',
      verified: true,
      score: 'C3 70/100',
      thumbTone: 'linear-gradient(145deg,#FF0000,#FF8A80)',
    },
    {
      id: 'hp5',
      handle: '@infoumkm.id',
      platform: 'tiktok',
      excerpt:
        'Data sensus UMKM kalian dipakai buat narik cicilan KUR ganda!! Cek sekarang sebelum kena!!',
      likes: '892',
      retweets: '61,4 rb',
      tone: 'rev',
      toneLabel: 'Negatif · Hoaks',
      influencer: true,
      score: 'C6 22/100',
      sourceUrl: 'https://www.tiktok.com/',
      thumbTone: 'linear-gradient(145deg,#F97316,#FDBA74)',
    },
    {
      id: 'hp6',
      handle: 'Antara News',
      platform: 'news',
      excerpt:
        'Kementerian UMKM catat realisasi KUR capai 61 persen dari target tahun berjalan pada semester I 2026.',
      likes: '1.980',
      retweets: '4,2 jt',
      tone: 'rev',
      toneLabel: 'Netral',
      verified: true,
      score: 'C3 74/100',
      thumbTone: 'linear-gradient(145deg,#1E8E5A,#86EFAC)',
    },
    {
      id: 'hp7',
      handle: '@pengusaha_muda',
      platform: 'threads',
      excerpt:
        'Program kemitraan UMKM sama usaha besar ini konsepnya bagus, tinggal eksekusi di lapangan yang perlu dikawal.',
      likes: '74',
      retweets: '9,8 rb',
      tone: 'done',
      toneLabel: 'Positif',
      score: 'C2 69/100',
      thumbTone: 'linear-gradient(145deg,#000000,#6B7280)',
    },
  ],
  crisisIssues: [
    {
      title: 'Hoaks "data KUR ditarik via tautan phishing"',
      detail: 'Reach 12,8 jt · emosi takut+marah',
      source: 'TikTok → X',
      mentions: '3.640 · ▲ cepat',
      sla: '0:47:28',
      pic: 'Koord. Krisis L2',
      status: 'BERJALAN',
      statusTone: 'proc',
      severity: 'high',
    },
    {
      title: 'Petugas palsu tawarkan "percepatan sertifikasi halal',
      detail: 'Terlapor: Bekasi, Bogor, Medan',
      source: 'WA, Facebook',
      mentions: '1.120 · stabil',
      sla: '6:10:00',
      pic: 'Tim Verifikasi',
      status: 'DILAPORKAN',
      statusTone: 'rep',
      severity: 'medium',
    },
    {
      title: 'Penipuan pinjaman online mengatasnamakan KUR',
      detail: '3 provinsi',
      source: 'X, komunitas FB',
      mentions: '860 · ▼ turun',
      sla: '9:40:00',
      pic: 'Humas Daerah',
      status: 'MITIGASI',
      statusTone: 'proc',
      severity: 'medium',
    },
    {
      title: 'Keluhan proses onboarding Sapa UMKM lambat',
      detail: 'Sporadis, 5 kota',
      source: 'Play Store, IG',
      mentions: '310 · stabil',
      sla: '20:00:00',
      pic: 'Tim Sapa UMKM',
      status: 'MONITOR',
      statusTone: 'rev',
      severity: 'low',
    },
    {
      title: 'Situs abal meniru identitas Kementerian UMKM',
      detail: 'Domain phishing pendaftaran KUR',
      source: 'Web, laporan warga',
      mentions: '402 · ▲ lambat',
      sla: '16:15:00',
      pic: 'Tim Cyber',
      status: 'DILAPORKAN',
      statusTone: 'rep',
      severity: 'low',
    },
    {
      title: 'Narasi "sertifikasi halal',
      detail: 'Varian klaim, Jawa & Sumatra',
      source: 'TikTok, Reels',
      mentions: '588 · stabil',
      sla: '18:30:00',
      pic: 'Digital Army',
      status: 'KONTRA-NARASI',
      statusTone: 'proc',
      severity: 'low',
    },
    {
      title: 'FAQ "apakah data UMKM dibagikan ke pihak ketiga?"',
      detail: 'Lonjakan intent bot WA · bukan hoaks terstruktur',
      source: 'WA Official',
      mentions: '1.740 sesi · edukasi',
      sla: '22:50:00',
      pic: 'WA Desk',
      status: 'EDUKASI',
      statusTone: 'done',
      severity: 'low',
    },
  ],
  crisisTimeline: [
    {
      time: '28 JUL · 19.10',
      text: 'Video hoaks tayang di TikTok @infoumkm.id — klaim data KUR dipakai tarik cicilan ganda.',
      tone: 'crit',
    },
    {
      time: '28 JUL · 21.30',
      text: 'Viral: 390 rb views, direpost 2 akun besar X. Velocity +180%.',
      tone: 'crit',
    },
    {
      time: '29 JUL · 08.30',
      text: 'Klarifikasi resmi Kementerian UMKM terbit — dikutip 18 media.',
      tone: 'good',
    },
    {
      time: '29 JUL · 11.00',
      text: 'Posko L2 berkoordinasi dengan perbankan Himbara & Kemenkomdigi.',
      tone: 'good',
    },
    {
      time: '29 JUL · 14.30',
      text: 'Velocity sentimen negatif melandai −18%, narasi hoaks terkendali.',
      tone: 'good',
    },
  ],
  crisisAmplifiers: [
    {
      handle: '@infoumkm.id',
      note: 'Video hoaks pertama tayang',
      platform: 'TikTok',
      followers: '61.400',
      reach: '10,2 jt',
      role: 'Originator',
      sentiment: 'Negatif',
    },
    {
      handle: '@beritaviral.id',
      note: 'Repost pertama <2 jam setelah unggahan asli',
      platform: 'X (Twitter)',
      followers: '890.000',
      reach: '4,1 jt',
      role: 'Amplifier',
      sentiment: 'Negatif',
    },
    {
      handle: '@info_ekonomi',
      note: 'Thread analisis, banyak dikutip akun lain',
      platform: 'X (Twitter)',
      followers: '512.000',
      reach: '2,3 jt',
      role: 'Amplifier',
      sentiment: 'Negatif',
    },
    {
      handle: 'Warga Peduli UMKM',
      note: 'Grup diskusi, ramai perdebatan pro-kontra',
      platform: 'Facebook',
      followers: '340.000 anggota',
      reach: '1,1 jt',
      role: 'Penyebar Sekunder',
      sentiment: 'Netral–Negatif',
    },
    {
      handle: '@faktachecker.id',
      note: 'Thread klarifikasi, mengutip pernyataan resmi',
      platform: 'X (Twitter)',
      followers: '220.000',
      reach: '980 rb',
      role: 'Kontra-Narasi',
      sentiment: 'Positif',
    },
  ],
  crisisChannelReach: [
    { channel: 'TikTok', reach: '10,2 jt', posPct: 18 },
    { channel: 'X (Twitter)', reach: '6,4 jt', posPct: 24 },
    { channel: 'Online News', reach: '3,2 jt', posPct: 92 },
    { channel: 'Instagram & Reels', reach: '2,8 jt', posPct: 64 },
    { channel: 'Facebook & grup', reach: '1,1 jt', posPct: 41 },
    { channel: 'Threads', reach: '540 rb', posPct: 55 },
  ],
  crisisHashtags: [
    '#HoaksKUR',
    '#CicilanGanda',
    '#KURPalsu',
    '#WaspadaPenipuan',
    '#KlarifikasiKUR',
    '#PhishingKUR',
    '#TolakHoaks',
    '#DataUMKM',
    '#SertifikasiHalalPalsu',
    '#SapaUMKMAman',
    '#PenipuanOnline',
    '#UMKMWaspada',
  ],
  minister: {
    name: 'Maman Abdurrahman',
    title: 'Menteri Usaha Mikro, Kecil, dan Menengah RI',
    since: 'Menjabat sejak 21 Okt 2024',
    cabinet: 'Kabinet Merah Putih',
    party: 'Partai Golkar',
    history: 'Anggota DPR RI (2018–2024)',
    birth: 'Lahir 10 September 1980',
    photoNote:
      'Foto contoh untuk kebutuhan mockup — ganti dengan foto resmi dari Biro Humas & Protokol Kementerian UMKM sebelum dipakai produksi.',
  },
  ministerNews: [
    {
      title: 'Menteri UMKM tinjau langsung sentra sertifikasi halal',
      context: 'Kunjungan kerja, Jawa Tengah',
      source: 'TVRI, Kompas',
      tone: 'pos',
      toneLabel: 'Positif',
      reach: '4,1 jt',
      time: '2 jam lalu',
    },
    {
      title: 'Pernyataan soal percepatan realisasi KUR di semester II',
      context: 'Konferensi pers, Jakarta',
      source: 'Antara, CNBC',
      tone: 'pos',
      toneLabel: 'Positif',
      reach: '2,8 jt',
      time: '5 jam lalu',
    },
    {
      title: 'Kritik pengamat soal target digitalisasi Sapa UMKM',
      context: 'Opini media, ekonomi digital',
      source: 'Portal ekonomi',
      tone: 'neu',
      toneLabel: 'Netral',
      reach: '860 rb',
      time: '8 jam lalu',
    },
    {
      title: 'Isu tudingan konflik kepentingan mitra program (belum terverifikasi)',
      context: 'Unggahan media sosial X, forum',
      source: 'X, forum',
      tone: 'neg',
      toneLabel: 'Negatif',
      reach: '410 rb',
      time: '12 jam lalu',
    },
    {
      title: 'Apresiasi pelaku UMKM atas kemudahan izin usaha',
      context: 'Liputan lapangan',
      source: 'Detik, Liputan6',
      tone: 'pos',
      toneLabel: 'Positif',
      reach: '1,2 jt',
      time: '1 hari lalu',
    },
  ],
  quotes: [
    {
      text: 'Target sertifikasi halal',
      context: 'Konferensi pers · 29 Jul 2026',
      responses: '3.400 respons, 82% mendukung',
      supportPct: 82,
    },
    {
      text: 'Kami buka aduan langsung bila ada pihak yang menyalahgunakan nama program KUR.',
      context: 'Wawancara media · 27 Jul 2026',
      responses: '1.900 respons, 90% mendukung',
      supportPct: 90,
    },
    {
      text: 'Program kemitraan usaha besar dan UMKM akan terus kami dorong agar rantai pasok lebih adil.',
      context: 'Kunjungan kerja · 26 Jul 2026',
      responses: '1.240 respons, 76% mendukung',
      supportPct: 76,
    },
    {
      text: 'Tudingan konflik kepentingan terkait mitra program tidak berdasar, kami akan buka data secara transparan.',
      context: 'Konferensi pers · 25 Jul 2026',
      responses: '2.150 respons, 68% mendukung',
      supportPct: 68,
    },
  ],
  schedule: [
    { title: 'Peresmian sentra UMKM digital', when: '31 Jul', where: 'Surabaya', media: '6 media' },
    { title: 'Rapat kerja realisasi KUR semester II', when: '3 Agu', where: 'Jakarta', media: 'Internal' },
    { title: 'Kunjungan sentra sertifikasi halal', when: '5 Agu', where: 'Makassar', media: '4 media' },
    { title: 'Dialog kemitraan UMKM & usaha besar', when: '7 Agu', where: 'Bandung', media: '5 media' },
  ],
  dominantTopics: [
    { name: 'sertifikasi halal', count: '412 berita' },
    { name: 'Realisasi KUR', count: '356 berita' },
    { name: 'Digitalisasi / Sapa UMKM', count: '241 berita' },
    { name: 'Kemitraan usaha besar–UMKM', count: '158 berita' },
    { name: 'Isu personal / kunjungan kerja', count: '117 berita' },
  ],
  sourceTotals: [
    { label: 'X / Tweets', value: '241.748', kind: 'tweets' },
    { label: 'Instagram', value: '452', kind: 'posts' },
    { label: 'Facebook', value: '1.540', kind: 'posts' },
    { label: 'TikTok', value: '3.241', kind: 'posts' },
    { label: 'YouTube', value: '1.901', kind: 'posts' },
    { label: 'Threads', value: '2.680', kind: 'posts' },
    { label: 'Online News', value: '43.305', kind: 'articles' },
  ],
  personalInsight:
    'Isu tudingan konflik kepentingan mitra program masih berreach rendah (410 rb) dan belum diliput media arus utama — rekomendasi: siapkan klarifikasi tertulis, tidak perlu konferensi pers.',
  authors: [
    // Influential — from HTML Top 10 Authors
    { name: 'Indosiar', site: 'YouTube', mentions: 1, engagement: 33, followers: '35.600.000', group: 'influential' },
    { name: 'detikcom', site: 'X', mentions: 5, engagement: 11, followers: '23.625.890', group: 'influential' },
    { name: 'KOMPASTV', site: 'YouTube', mentions: 3, engagement: 111, followers: '20.000.000', group: 'influential' },
    { name: 'tvOneNews', site: 'YouTube', mentions: 3, engagement: 6, followers: '16.300.000', group: 'influential' },
    { name: 'CNN Indonesia', site: 'YouTube', mentions: 3, engagement: 18, followers: '12.000.000', group: 'influential' },
    { name: 'METRO TV', site: 'YouTube', mentions: 11, engagement: 78, followers: '11.200.000', group: 'influential' },
    { name: 'Tribun Timur', site: 'YouTube', mentions: 3, engagement: 19, followers: '9.390.000', group: 'influential' },
    { name: 'METRO TV', site: 'X', mentions: 56, engagement: 1354, followers: '8.760.000', group: 'influential' },
    { name: 'Kompas.com', site: 'X', mentions: 12, engagement: 53, followers: '7.977.063', group: 'influential' },
    // Active
    { name: '@ekonomi_rakyat', site: 'X', mentions: 18, engagement: 210, followers: '42.300', group: 'active' },
    { name: 'Forum UMKM Nusantara', site: 'FB', mentions: 14, engagement: 165, followers: '88.900', group: 'active' },
    { name: '@ratnasari.umkm', site: 'IG', mentions: 9, engagement: 340, followers: '15.200', group: 'active' },
    { name: '@infoumkm.id', site: 'TikTok', mentions: 6, engagement: 892, followers: '61.400', group: 'active' },
    { name: '@pengusaha_muda', site: 'Threads', mentions: 5, engagement: 74, followers: '9.800', group: 'active' },
    { name: 'Kompas TV', site: 'YouTube', mentions: 3, engagement: 96, followers: '20.000.000', group: 'active' },
    // Portal News
    { name: 'Kompas.com', site: 'Portal', mentions: 412, engagement: 3100, followers: '7.977.063', group: 'portal' },
    { name: 'Detik.com', site: 'Portal', mentions: 356, engagement: 2640, followers: '6.500.000', group: 'portal' },
    { name: 'Antara News', site: 'Portal', mentions: 298, engagement: 1980, followers: '4.200.000', group: 'portal' },
    { name: 'CNBC Indonesia', site: 'Portal', mentions: 241, engagement: 1410, followers: '3.100.000', group: 'portal' },
    { name: 'Liputan6.com', site: 'Portal', mentions: 190, engagement: 1020, followers: '2.800.000', group: 'portal' },
    { name: 'Tribunnews.com', site: 'Portal', mentions: 158, engagement: 890, followers: '5.400.000', group: 'portal' },
  ],
  programs: [
    {
      name: 'sertifikasi halal',
      partner: 'Kerja sama BPJPH',
      target: '500.000 UMKM',
      realization: '312.400 (62%)',
      pct: 62,
      trend: 'stabil',
      trendTone: 'flat',
      status: 'accelerate',
      statusLabel: 'PERLU AKSELERASI',
    },
    {
      name: 'Realisasi KUR',
      partner: 'Sinergi perbankan himbara',
      target: '100% pagu TA26',
      realization: '61%',
      pct: 61,
      trend: 'naik',
      trendTone: 'up',
      status: 'on_track',
      statusLabel: 'ON TRACK',
    },
    {
      name: 'Digitalisasi Sapa UMKM',
      partner: 'Onboarding platform terpadu',
      target: '57 jt UMKM',
      realization: '8,4 jt (15%)',
      pct: 15,
      trend: 'naik',
      trendTone: 'up',
      status: 'accelerate',
      statusLabel: 'PERLU AKSELERASI',
    },
    {
      name: 'Kemitraan Usaha Besar–UMKM',
      partner: 'Rantai pasok & pengadaan',
      target: '1.200 kemitraan',
      realization: '740 (62%)',
      pct: 62,
      trend: 'stabil',
      trendTone: 'flat',
      status: 'on_track',
      statusLabel: 'ON TRACK',
    },
    {
      name: 'Pengadaan Barang/Jasa Pemerintah untuk UMKM',
      partner: 'Alokasi belanja K/L & Pemda',
      target: 'Rp 400 T',
      realization: 'Rp 218 T (55%)',
      pct: 55,
      trend: 'melambat',
      trendTone: 'down',
      status: 'risk',
      statusLabel: 'RISIKO',
    },
    {
      name: 'Modernisasi Koperasi',
      partner: 'Koperasi Merah Putih',
      target: '80.000 koperasi',
      realization: '51.200 (64%)',
      pct: 64,
      trend: 'naik',
      trendTone: 'up',
      status: 'on_track',
      statusLabel: 'ON TRACK',
    },
  ],
  programSentiment: [
    { name: 'Realisasi KUR', posPct: 74 },
    { name: 'sertifikasi halal', posPct: 66 },
    { name: 'Digitalisasi Sapa UMKM', posPct: 52 },
    { name: 'Pengadaan Barang/Jasa Pemerintah', posPct: 41 },
    { name: 'Kemitraan Usaha Besar–UMKM', posPct: 69 },
  ],
  programConstraints: [
    { issue: 'Verifikator halal terbatas di luar Jawa', program: 'sertifikasi halal', level: 'monitor' },
    { issue: 'Literasi digital pelaku usaha mikro rendah', program: 'Sapa UMKM', level: 'monitor' },
    { issue: 'Realisasi belanja Pemda tertinggal target', program: 'Pengadaan Pemerintah', level: 'risk' },
  ],
  regionAchievements: [
    { name: 'Jawa Timur', pct: 88 },
    { name: 'Jawa Barat', pct: 84 },
    { name: 'Jawa Tengah', pct: 81 },
    { name: 'Sumatera Utara', pct: 67 },
    { name: 'Papua', pct: 29, note: 'perlu perhatian' },
  ],
  milestones: [
    { when: 'Okt 2026', text: 'Batas wajib sertifikasi halal' },
    { when: 'Sep 2026', text: 'Evaluasi tengah tahun realisasi KUR' },
    { when: 'Agu 2026', text: 'Target onboarding 10 juta akun Sapa UMKM' },
    { when: 'Jul 2026', text: 'Peluncuran gelombang ke-2 sertifikasi halal' },
  ],
  ticker: [
    {
      tag: 'hoax',
      tagLabel: 'UPDATE',
      text: 'Klarifikasi resmi hoaks KUR telah dikutip 18 media nasional',
    },
    {
      tag: 'program',
      tagLabel: 'PROGRAM',
      text: 'Realisasi KUR semester I mencapai 61% dari target tahun berjalan',
    },
    {
      tag: 'media',
      tagLabel: 'MEDIA',
      text: 'Kunjungan Menteri ke sentra sertifikasi halal',
    },
    {
      tag: 'isu',
      tagLabel: 'ISU',
      text: 'Situs phishing pendaftaran KUR dilaporkan ke tim cyber',
    },
  ],
  insight:
    'Lonjakan <strong>+180% percakapan negatif</strong> pada 28 Jul 19.00–22.00 WIB dipicu video TikTok @infoumkm.id soal hoaks "data KUR dipakai untuk menarik cicilan ganda". Klarifikasi resmi menurunkan velocity ke <strong>−18%</strong>.',
  programInsight:
    '2 dari 6 program berstatus "Perlu Akselerasi", 1 program berisiko (Pengadaan Barang/Jasa Pemerintah) — rekomendasi rapat koordinasi dengan Pemda tertinggal.',
  crisisInsight:
    'Isu tudingan konflik kepentingan mitra program masih berreach rendah (410 rb) dan belum diliput media arus utama — rekomendasi: siapkan klarifikasi tertulis, tidak perlu konferensi pers. Untuk ISU-0032 Hoaks KUR: prioritaskan akun amplifier untuk diajak klarifikasi bersama.',
};

UMKM_MOCK.mapTop = UMKM_MOCK.mapBubbles
  .slice()
  .sort((a, b) => b.volume - a.volume)
  .slice(0, 5);
